# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'teslaMote' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for teslaMote
  pod 'TeslaSwift'
  pod 'EasyFutures'

  target 'teslaMoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'teslaMoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
